"""Create Tables

Revision ID: cb515fac1b65
Revises: 
Create Date: 2024-10-19 16:31:56.078015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb515fac1b65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('NAME', sa.TEXT(), nullable=False),
    sa.Column('AGE', sa.INTEGER(), nullable=False),
    sa.Column('TOWN', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('NAME')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
